Doorsteps.Experiments.Web/Controllers/ExperimentsController.cs
/***************************************************************************************************
 * 
 * Filename:    ExperimentController.cs 
 * Description: Implementation - Provides a website to use for interacting with Experiments.
 * 
 * Author:      Glenn Aitchison
 * Date:        29-Mar-2022
 * 
 ***************************************************************************************************/

// Include Microsoft libraries we need
using System.Text;
using Microsoft.AspNetCore.Mvc;

// Include NewtonSOFT JSON libraries
using Newtonsoft.Json;

// Include RestSharp libraries we need to include
using RestSharp;

// Include Spring libraries we need 
using Spring.Context;
using Spring.Context.Support;

// Include custom code we need
using Doorsteps.Experiments.Models;

namespace Doorsteps.Experiments.Web
{
     /// <summary>
     ///    Allows user to interact with Experiments.
     /// </summary>
     [Route("/")]
     public class ExperimentsController : Controller
     {
          #region Setup and Initialization

               // Setup variables
               private IApplicationContext _experimentsWebApp;     // Application that will interact to get experiments from JSON data files
               private RestClient          _experimentsApi;        // RESTful APIs to interact with

               /// <summary>
               ///    Create a website to allow user to interact with Experiments.
               /// </summary>
               public ExperimentsController()
               {
                    // Get application context from spring - basically the application once all dependencies have been injected
                    _experimentsWebApp = ContextRegistry.GetContext();

                    // Get experiments API
                    _experimentsApi = (RestClient) _experimentsWebApp.GetObject("myExperimentsApi");
               }  // End ExperimentsController

          #endregion

          #region Methods 

               #region Common Functionality 

                    /// <summary>
                    ///    Deserialize JSON data to objects.
                    /// </summary>
                    /// <param name="restfulResponse">A RESTful response received from APIs.</param>
                    /// <returns>Objects generated from JSON data.</returns>
                    private T? DeserializeData<T>(RestResponse restfulResponse)
                    {
                         // Setup variables                                                                                       
                         JsonSerializer jsonSerializer =              // Create a JSON serializer - converts JSON data to objects
                                           JsonSerializer.Create(new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All });

                         // Convert JSON data to .Net Objects
                         using (StringReader jsonTextReader = new StringReader(restfulResponse.Content ?? ""))
                         using (JsonTextReader jsonStream = new JsonTextReader(jsonTextReader)) { return jsonSerializer.Deserialize<T>(jsonStream); }
                    }  // End DeserializeData

                    /// <summary>
                    ///    Execute RESTful request.
                    /// </summary>
                    /// <param name="restfulRequest">A RESTful request.</param>
                    /// <returns></returns>
                    private RestResponse ExecuteRestfulRequest<T>(RestRequest restfulRequest, T? jsonObject)
                    {
                         // Setup variables
                         StringBuilder  jsonData       = new StringBuilder();    // JSON data
                         JsonSerializer jsonSerializer =                         // JSON serializer - converts data from JSON to objects - make sure we send thro types to make inheritance work
                                           JsonSerializer.Create(new JsonSerializerSettings() { TypeNameHandling = TypeNameHandling.All });   

                         // If we want to pass an object (as JSON) to web service then do so!
                         if (jsonObject != null)
                         {
                              using (StringWriter jsonDataStream = new StringWriter(jsonData)) 
                              { jsonSerializer.Serialize(jsonDataStream, jsonObject); restfulRequest.AddStringBody(jsonData.ToString(), "application/json"); }  
                         }  // End if 

                         // Run the request against the APIs
                         return _experimentsApi.ExecuteAsync(restfulRequest).Result;
                    }  // End ExecuteRestfulRequest

                    /// <summary>
                    ///    Get a list of all experiments.
                    /// </summary>
                    /// <returns>A list of all experiments.</returns>
                    private List<Experiment> GetAllExperiments()
                    {
                         // Setup variables
                         List<Experiment>? myExperiments;                  // List of experiments found
                         RestResponse      restfulResponse;                // RESTful API response

                         // Get all experiments
                         restfulResponse = ExecuteRestfulRequest<IExperiment>(new RestRequest("/all", Method.Get), null);

                         // Show thank you page or error dependant if everything went okay
                         if (!restfulResponse.IsSuccessful) return new List<Experiment>();

                         // Get a list of current experiments  
                         myExperiments = DeserializeData<List<Experiment>>(restfulResponse) ?? new List<Experiment>();                                                       

                         // Return list of experiments
                         return myExperiments;
                    }  // End GetAllExperiments

                    /// <summary>
                    ///    Get a list of all experiments.
                    /// </summary>
                    /// <returns>A list of all experiments.</returns>
                    private List<Experiment> GetAllResponses()
                    {
                         // Setup variables
                         List<Experiment>? myExperiments;                  // List of experiments found
                         RestResponse      restfulResponse;                // RESTful API response

                         // Get all responses from experiments
                         restfulResponse = ExecuteRestfulRequest<IExperiment>(new RestRequest("/responses", Method.Get), null);

                         // Show thank you page or error dependant if everything went okay
                         if (!restfulResponse.IsSuccessful) return new List<Experiment>();

                         // Get a list of current experiments  
                         myExperiments = DeserializeData<List<Experiment>>(restfulResponse) ?? new List<Experiment>();                                                       

                         // Return list of responses from experiments
                         return myExperiments;
                    }  // End GetAllResponses

               #endregion

               #region Routes

                    /// <summary>
                    ///    Add an experiment.
                    /// </summary>
                    /// <param name="myExperiment">The experiment you wish to add questions to.</param>
                    /// <param name="questionCategory">The category of the question (standard or custom)/</param>
                    /// <param name="typeOfQuestion">The type of the question - i.e. SingeLineQuestion, MultiLineQuesiton, or SelectAnOptionQuest.</param>
                    /// <param name="operationMode">The mode of operation.</param>
                    [HttpPost]
                    [HttpGet]
                    [Route("AddExperiment")]
                    public IActionResult AddExperiment([ModelBinder(BinderType = typeof(ExperimentsModelBinder))] Experiment myExperiment, String questionCategory, String typeOfQuestion, String operationMode = "")
                    {
                         // Setup variables
                         RestResponse restfulResponse;                     // Response from RESTful APIs             
                         Experiment?  templateExperiment;                  // Template experiment

                         // Get experiments from template
                         if (operationMode.Equals(""))
                         { 
                              templateExperiment = GetAllExperiments().Where(experiment => experiment.Name.Equals("[Template Experiment]", StringComparison.InvariantCultureIgnoreCase)).FirstOrDefault();
                              if (templateExperiment != null) { myExperiment = templateExperiment; myExperiment.Name = ""; }
                         }  // End if 

                         // Remove TEMPLATE answer when when are not adding an answer - otherwise it will be included
                         if (!operationMode.Equals("Add Answer"))
                         {
                              // Remove template answer from any select an option questions that are standard ones
                              foreach (IQuestion question in myExperiment.StandardQuestionsToAsk)
                              {
                                   if (question.GetType() == typeof(SelectAnOptionQuestion))
                                   { SelectAnOptionQuestion myQuestion = (SelectAnOptionQuestion) question; myQuestion.PossibleAnswers.RemoveAt(myQuestion.PossibleAnswers.Count - 1); }
                              }  // End foreach

                              // Remove template answer from any select an option questionsthat are standard ones

Doorsteps.Experiments.Web/Views/Experiments/AddExperiment.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@using Doorsteps.Experiments.Models
@model Doorsteps.Experiments.Models.Experiment

<!-- Add an experimentand questions that need to be answered -->
@using (Html.BeginForm("AddExperiment", "Experiments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     <!-- Experiments Heading -->
     <h2><b>Add Experiment</b></h2>

    <table border="0" cellpadding="0" cellspacing="0" style="padding-left: 15px; padding-bottom: 10px; width: 600px;">

          <!-- Display name and description of experiment -->
          <tr class="text" style="width: 100px;"><td class="text">&nbsp;Name:&nbsp;</td><td>@Html.TextBoxFor(model => model.Name)</td></tr>
          <tr class="text" style="width: 100px;"><td>&nbsp;Description:&nbsp;</td><td>@Html.TextBoxFor(model => model.Description)</td></tr>
                    
          <!-- Display Add Question Heading and input fields to add question -->
          <tr class="text"><td colspan="2" style="height: 30px; padding-top: 15px; padding-bottom: 10px;"><b>Add Question</b></td></tr>
          <tr class="text">
               <td colspan="2">

                    <!-- Type of Question to Add -->
                    <select name="questionCategory" class="text">
                         <option>Standard</option>
                         <option>Custom</option>
                    </select>


                    <!-- Type of Question to Add -->
                    <select name="typeOfQuestion" class="text">
                         <option>Single Line</option>
                         <option>Multi Line</option>
                         <option>Select An Option</option>
                    </select>

                    <!-- Add a Question-->
                    <input type="submit" id="AddQuestion" name="operationMode" value="Add Question" class="text"/>

               </td>
          </tr>

          <!-- Display Questionaire -->
          <tr class="text"><td colspan="2" style="height: 30px; padding-top: 15px; padding-bottom: 10px;"><b>Questionaire</b></td></tr>
          <tr class="text">
               <td colspan="2">

                    <table border="0" cellpadding="0" cellspacing="0" style="padding-left: 15px;">

                         <!-- Display the standard questions header -->
                         <tr class="text"><td colspan="2" style="height: 10px;"><b id="standard_questions">Standard Questions</b></td></tr>

                         <!-- Display friendly message if no questions found -->
                         @if (Model.StandardQuestionsToAsk.Count == 0)
                         { 
                              @:<tr class="text"><td colspan="2"><div class="Text">There are no questions found.</div></td></tr> 
                         }

                         <!-- Display standard questions that have been added -->
                         @for(int i=0; i < Model.StandardQuestionsToAsk.Count; i++)
                         {
                              <tr class="text">
                                   
                                   <!-- Display Prompt -->
                                   <td style="vertical-align: top; padding-top: 5px;">
                                        <b>Prompt</b><br/>
                                        @Html.TextBoxFor(model => model.StandardQuestionsToAsk[i].Prompt, null, new { Class = "Text" })&nbsp;&nbsp;&nbsp;
                                   </td>

                                   <!-- Display Question -->
                                   <td class="text" style="vertical-align: top; padding-top: 5px;">

                                        <!-- Display Answer Section -->
                                        <b>Answer</b><br/>
                                        @{ Type typeOfStandardQuestion = Model.StandardQuestionsToAsk[i].GetType(); }
                                        @if (typeOfStandardQuestion.Equals(typeof(SingleLineQuestion)))      @Html.TextBoxFor(model      => model.StandardQuestionsToAsk[i].Answer, null, new { Class = "Text" })
                                        @if (typeOfStandardQuestion.Equals(typeof(MultiLineQuestion)))       @Html.TextAreaFor(model     => model.StandardQuestionsToAsk[i].Answer, 5, 5, new { Class = "Text", Style="width: 300px; height: 100px;" })
                                        
                                        <!-- Type of Question -->
                                        @Html.HiddenFor(model => model.StandardQuestionsToAsk[i].Type)

                                        <!-- If question is 'Select An Option'' then allow users to add possible answers -->
                                        @{
                                             if (typeOfStandardQuestion.Equals(typeof(SelectAnOptionQuestion))) 
                                             {
                                                  SelectAnOptionQuestion selectAnOptionQuestion = (SelectAnOptionQuestion) Model.StandardQuestionsToAsk[i];
                                                  for(int a = 0; a < selectAnOptionQuestion.PossibleAnswers.Count; a++)
                                                  {
                                                       @Html.TextBox("StandardQuestionsToAsk[" + i + "].PossibleAnswers[" + a + "]", null, new { Class = "Text" });
                                                       <br/>
                                                  }
                                                  @Html.Hidden("StandardQuestionsToAsk[" + i + "].PossibleAnswers[" + selectAnOptionQuestion.PossibleAnswers.Count + "]", "<<TEMPLATE ANSWER>>")
                                                  @:<input type="submit" id="AddAnswer" name="operationMode" value="Add Answer"/>
                                             }
                                        }

                                   </td>
                              </tr>
                         }
                         
                         <!-- Display the custom questions header -->
                         <tr class="text"><td colspan="2" style="height: 10px; padding-top: 15px;"><b id="custom_questions">Additional Questions</b></td></tr>
                    
                         <!-- Display friendly message if no questions found -->
                         @if ((Model ?? new Experiment()).CustomQuestionsToAsk.Count == 0)
                         {
                              @:<tr class="text"><td colspan="2"><div class="Text">There are no questions found.</div></td></tr>
                         }

                         <!-- Display custom questions that have been added -->
                         @for(int i=0; i < (Model ?? new Experiment()).CustomQuestionsToAsk.Count; i++)
                         {
                              <!-- Display buttons to add a question -->
                              <tr class="text">
                                   <td style="vertical-align: top; padding-top: 5px;">
                                        <b>Prompt</b><br/>
                                        @Html.TextBoxFor(model => model.CustomQuestionsToAsk[i].Prompt, null, new { Class = "Text" })&nbsp;&nbsp;&nbsp;
                                   </td>
                                   <td class="text" style="vertical-align: top; padding-top: 5px;">

                                        <!-- Display Answer Section -->
                                        <b>Answer</b><br/>
                                        @{ Type typeOfCustomQuestion = (Model ?? new Experiment()).CustomQuestionsToAsk[i].GetType(); }
                                        @if (typeOfCustomQuestion.Equals(typeof(SingleLineQuestion)))      @Html.TextBoxFor(model      => model.CustomQuestionsToAsk[i].Answer, null, new { Class = "Text" })
                                        @if (typeOfCustomQuestion.Equals(typeof(MultiLineQuestion)))       @Html.TextAreaFor(model     => model.CustomQuestionsToAsk[i].Answer, 5, 5, new { Class = "Text", Style="width: 300px; height: 100px;" })

                                        <!-- Type of Question -->
                                        @Html.HiddenFor(model => model.CustomQuestionsToAsk[i].Type)

                                        <!-- If question is 'Select An Option'' then allow users to add possible answers -->
                                        @{
                                             if (typeOfCustomQuestion.Equals(typeof(SelectAnOptionQuestion))) 
                                             {
                                                  SelectAnOptionQuestion selectAnOptionQuestion = (SelectAnOptionQuestion) (Model ?? new Experiment()).CustomQuestionsToAsk[i];
                                                  for(int a = 0; a < selectAnOptionQuestion.PossibleAnswers.Count; a++)
                                                  {
                                                       @Html.TextBox("CustomQuestionsToAsk[" + i + "].PossibleAnswers[" + a + "]", null, new { Class = "Text" });
                                                       <br/>
                                                  }
                                                  @Html.Hidden("CustomQuestionsToAsk[" + i + "].PossibleAnswers[" + selectAnOptionQuestion.PossibleAnswers.Count + "]", "<<TEMPLATE ANSWER>>")
                                                  @:<input type="submit" id="AddAnswer" name="operationMode" value="Add Answer" Class="Text"/>
                                             }
                                        }

                                   </td>
                              </tr>

                              <!-- Gap -->
                              <tr><td colspan="2" sstyle="height: 50px"/></tr>

                              <!-- Experiment we are working with -->
                              @Html.HiddenFor(model => model.Name);
                         }

                    </table>
               </td>
          </tr>

    </table>

    <!-- Show button so user submit answers -->
    <input type="submit" id="AddExperiment" name="operationMode" value="Add Experiment" class="Text" style="margin-top: 5px"/>
}

<!-- Display link to return to list of experiments -->
<span class="text">
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</span>

Doorsteps.Experiments.Web/Views/Experiments/ExperimentAlreadyExists.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment already exists and link to return to list of experiments -->
<div class="text">
     The experiment you are trying to add already exists.
     <br/><br/>
     <a href="javascript:history.back()">Go Back</a>
</div>

Doorsteps.Experiments.Web/Views/Experiments/ExperimentDisabled.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment is disabled and link to return to list of experiments -->
<div class="text">
     The experiment you are trying to access is disabled. Please re-enable it before proceeding.
     <br/><br/>
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</div>

Doorsteps.Experiments.Web/Views/Experiments/ExperimentsUpdated.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display success heading -->
<h2><b>Experiments Updated</b></h2>

<!-- Display thank you for updating the status and link to return to list of experiments -->
<div class="text">
     Thank you for updating the status of the experiments. 
     <br/><br/>
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</div>

Doorsteps.Experiments.Web/Views/Experiments/IncompleteQuestions.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment has incomplete questions and link to return to list of experiments -->
<div class="text">
     The experiment has incomplete questions. Please ensure all questions have been provided. 
     <br/><br/>
     <a href="javascript:history.back()">Go Back</a>
</div>

Doorsteps.Experiments.Web/Views/Experiments/ListExperiments.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@using Doorsteps.Experiments.Models
@model List<Doorsteps.Experiments.Models.Experiment>

<!-- Display experiments heading -->
<h2><b>Experiments Overview</b></h2>

<!-- Display friendly instructions to user -->
<div class="text">
     <ul>
          <li>Please click on the name of the experiment you wish to respond to.</li>
          <li>Tick the experiments you wish to disable then click <b>Update Experiments</b>.</li>
     </ul>
     <br/>
</div>

<!-- Gap -->
<br/>

<!-- Display a list of experiments and allow user to select which ones to enable or disable -->
@using(Html.BeginForm("ToggleExperiments", "Experiments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     <table border="0" cellpadding="0" cellspacing="0" style="padding-left: 15px;">

          @for(int i = 0; i < Model.Count; i++)
          {
               <!-- Display name of experiment with tickbox -->
               <tr class="text">
                    <td style="width: 10px; vertical-align: middle;">
                         @Html.CheckBoxFor(model => model[i].IsDisabled) 
                    </td>
                    <td style="vertical-align: middle;"><b>@Html.ActionLink(Model[i].Name, "ShowQuestionaire", "Experiments", new { experimentName = Model[i].Name.Replace(" ", "-") }, new { id = Model[i].Name.Replace(" ", "-") })</b></td>
               </tr>

               <!-- Display description of experiment -->
               <tr class="text"><td/><td>@(Model[i].Description)</td></tr>

               <!-- Provide name of experiment so we know what experiment we are toggling -->
               @Html.HiddenFor(model => model[i].Name)

               <tr><td colspan="2" style="height: 5px"/></tr>
          }
          
     </table>

     <!-- Show button that allows user to enable/disable experiments -->
     <input type="button" id="AddExperiment" value="Add Experiment" class="Text" style="margin-top: 10px" onClick="javascript:location.href='/AddExperiment'"/>

     <!-- Show button that allows user to enable/disable experiments -->
     <input type="submit" id="UpdateExperiments" value="Update Experiments" class="Text" style="margin-top: 10px"/>
}

Doorsteps.Experiments.Web/Views/Experiments/NoExperimentName.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment has incomplete questions and link to return to list of experiments -->
<div class="text">
     The experiment has no name. Please provide a name for the experiment. 
     <br/><br/>
     <a href="javascript:history.back()">Go Back</a>
</div>

Doorsteps.Experiments.Web/Views/Experiments/NoQuestionsToAsk.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment has incomplete questions and link to return to list of experiments -->
<div class="text">
     The experiment has no questions. Please provide at least one standard question to ask. 
     <br/><br/>
     <a href="javascript:history.back()">Go Back</a>
</div>

Doorsteps.Experiments.Web/Views/Experiments/NoSuchExperiment.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that experiment does not exist and link to return to list of experiments -->
<div class="text">
     The experiment you are trying to access does not exist. Please provide an experiment that exists.
     <br/><br/>
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</div>

Doorsteps.Experiments.Web/Views/Experiments/ShowQuestionaire.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@using Doorsteps.Experiments.Models
@model Doorsteps.Experiments.Models.Experiment

<!-- Display name and description of experiment and questions that need to be answered -->
@using (Html.BeginForm("SubmitResponses", "Experiments", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
     <!-- Experiments Heading -->
     <h2><b>Experiment Questionaire</b></h2>

    <table border="0" cellpadding="0" cellspacing="0" style="padding-left: 15px;">

          <!-- Display name of experiment -->
          <tr class="text"><td class="text">&nbsp;Name:&nbsp;</td><td>@((Model??new Experiment()).Name)</td></tr>

          <!-- Display description of experiment -->
          <tr class="text"><td>&nbsp;Description:&nbsp;</td><td>@((Model??new Experiment()).Description)</td></tr>

          <!-- Display the standard questions -->
          <tr class="text"><td colspan="2" style="height: 10px; padding-top: 15px;"><b id="standard_questions">Standard Questions</b></td></tr>
          @if ((Model??new Experiment()).StandardQuestionsToAsk.Count == 0)
          { 
               @:<tr class="text"><td colspan="2"><div class="Text">There are no questions found.</div></td></tr> 
          }
          @for(int i=0; i < (Model??new Experiment()).StandardQuestionsToAsk.Count; i++)
          {
               <tr class="text">
                    <td style="vertical-align: middle; padding-top: 5px;">@((Model??new Experiment()).StandardQuestionsToAsk[i].Prompt)&nbsp;&nbsp;&nbsp;@Html.HiddenFor(model => model.StandardQuestionsToAsk[i].Prompt)</td>
                    <td class="text" style="vertical-align: top; padding-top: 5px;">
                         @if ((Model??new Experiment()).StandardQuestionsToAsk[i].GetType().Equals(typeof(SingleLineQuestion)))      @Html.TextBoxFor(model      => model.StandardQuestionsToAsk[i].Answer, null, new { Class = "Text" })
                         @if ((Model??new Experiment()).StandardQuestionsToAsk[i].GetType().Equals(typeof(MultiLineQuestion)))       @Html.TextAreaFor(model     => model.StandardQuestionsToAsk[i].Answer, 5, 5, new { Class = "Text", Style="width: 300px; height: 100px;" })
                         @if ((Model??new Experiment()).StandardQuestionsToAsk[i].GetType().Equals(typeof(SelectAnOptionQuestion)))  @Html.DropDownListFor(model => model.StandardQuestionsToAsk[i].Answer, new SelectList(((SelectAnOptionQuestion) (Model??new Experiment()).StandardQuestionsToAsk[i]).PossibleAnswers), null, new { Class = "Text" })
                    </td>
               </tr>
          }

          <!-- Display the custom questions -->
          <tr class="text"><td colspan="2" style="height: 10px; padding-top: 15px;"><b id="custom_questions">Additional Questions</b></td></tr>
          @if ((Model ?? new Experiment()).CustomQuestionsToAsk.Count == 0)
          {
               @:<tr class="text"><td colspan="2"><div class="Text">There are no questions found.</div></td></tr>
          }
          @for(int i=0; i < (Model??new Experiment()).CustomQuestionsToAsk.Count; i++)
          {
               <tr class="text">
                    <td style="vertical-align: top; padding-top: 10px;">@((Model??new Experiment()).CustomQuestionsToAsk[i].Prompt)&nbsp;&nbsp;&nbsp;@Html.HiddenFor(model => model.CustomQuestionsToAsk[i].Prompt)</td>
                    <td class="text" style="vertical-align: top; padding-top: 5px;">
                         @if ((Model??new Experiment()).CustomQuestionsToAsk[i].GetType().Equals(typeof(SingleLineQuestion)))      @Html.TextBoxFor(model      => model.CustomQuestionsToAsk[i].Answer, null, new { Class = "Text" })
                         @if ((Model??new Experiment()).CustomQuestionsToAsk[i].GetType().Equals(typeof(MultiLineQuestion)))       @Html.TextAreaFor(model     => model.CustomQuestionsToAsk[i].Answer, 5, 5, new { Class = "Text", Style="width: 300px; height: 100px;" })
                         @if ((Model??new Experiment()).CustomQuestionsToAsk[i].GetType().Equals(typeof(SelectAnOptionQuestion)))  @Html.DropDownListFor(model => model.CustomQuestionsToAsk[i].Answer, new SelectList(((SelectAnOptionQuestion) (Model??new Experiment()).CustomQuestionsToAsk[i]).PossibleAnswers), null, new { Class = "Text" })
                    </td>
               </tr>

               <!-- Experiment we are working with -->
               @Html.HiddenFor(model => model.Name);
          }
          
    </table>

    <br/>

    <!-- Show button so user submit answers -->
    <input type="submit" id="SubmitResponses" value="Submit Responses" class="text"/>
}

<!-- Display link to return to list of experiments -->
<span class="text">
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</span>

Doorsteps.Experiments.Web/Views/Experiments/SomethingWentWrong.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display error heading -->
<h2><b>An error has occurred</b></h2>

<!-- Display message that something went wrong and link to return to list of experiments -->
<div class="text">
     There was a problem - something went wrong. Please let your systems administrator know.
     <br/><br/>
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</div>

Doorsteps.Experiments.Web/Views/Experiments/ThankYou.cshtml
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<!-- Display success heading -->
<h2><b>Responses Submitted</b></h2>

<!-- Display thank you message and link to return to list of experiments -->
<div class="text">
     Thank you for answering the questions. Your responses have been submitted.
     <br/><br/>
     @Html.ActionLink("Return to Experiments", "ListExperiments", "Experiments")
</div>